name: CI Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to use v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to use v3
        with:
          node-version: '20'  # Updated to use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
